# Generated by Django 4.1.5 on 2023-01-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContacUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('number', models.IntegerField(max_length=30)),
                ('message', models.TextField(max_length=200)),
            ],
        ),
    ]
