# Generated by Django 4.1.5 on 2023-03-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='body',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
