# Generated by Django 4.1.5 on 2023-03-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_shop_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='insta1',
        ),
        migrations.AddField(
            model_name='setting',
            name='email',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
