# Generated by Django 4.1.5 on 2023-01-31 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactus_is_check'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='Message',
            new_name='message',
        ),
    ]
