# Generated by Django 4.1.5 on 2023-02-05 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_message_contactus_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='flow2',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='flow3',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='flow4',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='flow5',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='flow6',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='flow7',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='flow8',
        ),
    ]
