# Generated by Django 4.1.5 on 2023-02-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_gallery_flow2_remove_gallery_flow3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='insta2',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='insta3',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='insta4',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='insta5',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='insta6',
        ),
        migrations.AlterField(
            model_name='setting',
            name='insta1',
            field=models.ImageField(upload_to='media/ Setting'),
        ),
    ]
